//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSOBA
    {
        public string OIB { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public Nullable<decimal> ID_OSOBA { get; set; }
    }
}
